"""
Test queries implemented in Python.
Demonstrates the five required queries plus additional useful operations.
"""

from typing import List, Dict, Optional, Any
from datetime import date, datetime
from database import get_db_cursor


def get_revenue_by_server() -> List[Dict[str, Any]]:
    """
    Query 1: Find the total revenue generated by each server.
    Joins orders, order_items, menu_items, and employees.
    
    Returns:
        List of dictionaries with server revenue data.
    """
    query = """
        SELECT 
            e.employee_id,
            e.first_name || ' ' || e.last_name AS server_name,
            e.role,
            COUNT(DISTINCT o.order_id) AS total_orders,
            ROUND(SUM(oi.quantity * oi.unit_price), 2) AS gross_sales,
            ROUND(SUM(o.tip), 2) AS total_tips,
            ROUND(SUM(o.total), 2) AS total_revenue
        FROM employees e
        JOIN orders o ON e.employee_id = o.employee_id
        JOIN order_items oi ON o.order_id = oi.order_id
        WHERE o.status = 'Completed'
        GROUP BY e.employee_id, e.first_name, e.last_name, e.role
        ORDER BY total_revenue DESC
    """
    
    with get_db_cursor() as (conn, cursor):
        cursor.execute(query)
        results = cursor.fetchall()
        return [dict(row) for row in results]


def get_popular_menu_items(limit: int = 15) -> List[Dict[str, Any]]:
    """
    Query 2: List the most popular menu items by order count.
    
    Args:
        limit: Maximum number of items to return.
        
    Returns:
        List of dictionaries with menu item popularity data.
    """
    query = """
        SELECT 
            mi.item_id,
            mi.name AS item_name,
            c.name AS category,
            mi.price,
            COUNT(oi.order_item_id) AS times_ordered,
            SUM(oi.quantity) AS total_quantity_sold,
            ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_revenue
        FROM menu_items mi
        JOIN order_items oi ON mi.item_id = oi.item_id
        JOIN categories c ON mi.category_id = c.category_id
        JOIN orders o ON oi.order_id = o.order_id
        WHERE o.status = 'Completed'
        GROUP BY mi.item_id, mi.name, c.name, mi.price
        ORDER BY times_ordered DESC
        LIMIT ?
    """
    
    with get_db_cursor() as (conn, cursor):
        cursor.execute(query, (limit,))
        results = cursor.fetchall()
        return [dict(row) for row in results]


def get_above_average_customers() -> List[Dict[str, Any]]:
    """
    Query 3: Find customers who have spent more than the average customer total.
    Uses a subquery to calculate the average.
    
    Returns:
        List of dictionaries with high-spending customer data.
    """
    query = """
        SELECT 
            c.customer_id,
            c.first_name || ' ' || c.last_name AS customer_name,
            c.email,
            COUNT(o.order_id) AS order_count,
            ROUND(SUM(o.total), 2) AS total_spent,
            ROUND((SELECT AVG(customer_total) 
                   FROM (SELECT SUM(total) AS customer_total 
                         FROM orders 
                         WHERE customer_id IS NOT NULL AND status = 'Completed'
                         GROUP BY customer_id)), 2) AS avg_customer_spending
        FROM customers c
        JOIN orders o ON c.customer_id = o.customer_id
        WHERE o.status = 'Completed'
        GROUP BY c.customer_id, c.first_name, c.last_name, c.email
        HAVING SUM(o.total) > (
            SELECT AVG(customer_total) 
            FROM (SELECT SUM(total) AS customer_total 
                  FROM orders 
                  WHERE customer_id IS NOT NULL AND status = 'Completed'
                  GROUP BY customer_id)
        )
        ORDER BY total_spent DESC
    """
    
    with get_db_cursor() as (conn, cursor):
        cursor.execute(query)
        results = cursor.fetchall()
        return [dict(row) for row in results]


def get_overbooked_reservations(reservation_date: Optional[str] = None) -> List[Dict[str, Any]]:
    """
    Query 4: Find reservations where party size exceeds table capacity.
    
    Args:
        reservation_date: Optional date filter (YYYY-MM-DD format).
        
    Returns:
        List of dictionaries with overbooking data.
    """
    query = """
        SELECT 
            r.reservation_id,
            c.first_name || ' ' || c.last_name AS customer_name,
            c.phone,
            t.table_number,
            t.capacity AS table_capacity,
            r.party_size,
            r.reservation_date,
            r.reservation_time,
            r.status,
            r.special_requests
        FROM reservations r
        JOIN customers c ON r.customer_id = c.customer_id
        JOIN tables t ON r.table_id = t.table_id
        WHERE r.party_size > t.capacity
    """
    
    params = []
    if reservation_date:
        query += " AND r.reservation_date = ?"
        params.append(reservation_date)
    
    query += " ORDER BY r.reservation_date, r.reservation_time"
    
    with get_db_cursor() as (conn, cursor):
        cursor.execute(query, params)
        results = cursor.fetchall()
        return [dict(row) for row in results]


def update_category_prices(category_name: str, percentage_increase: float) -> int:
    """
    Query 5: Update prices of all items in a category by a percentage.
    
    Args:
        category_name: Name of the category to update.
        percentage_increase: Percentage to increase (e.g., 10 for 10%).
        
    Returns:
        Number of items updated.
    """
    multiplier = 1 + (percentage_increase / 100)
    
    query = """
        UPDATE menu_items
        SET price = ROUND(price * ?, 2)
        WHERE category_id = (SELECT category_id FROM categories WHERE name = ?)
    """
    
    with get_db_cursor() as (conn, cursor):
        cursor.execute(query, (multiplier, category_name))
        return cursor.rowcount


def get_category_prices(category_name: str) -> List[Dict[str, Any]]:
    """
    Preview prices for a category before updating.
    
    Args:
        category_name: Name of the category.
        
    Returns:
        List of menu items with current prices.
    """
    query = """
        SELECT 
            mi.item_id,
            mi.name,
            c.name AS category,
            mi.price
        FROM menu_items mi
        JOIN categories c ON mi.category_id = c.category_id
        WHERE c.name = ?
        ORDER BY mi.name
    """
    
    with get_db_cursor() as (conn, cursor):
        cursor.execute(query, (category_name,))
        results = cursor.fetchall()
        return [dict(row) for row in results]


# ============================================
# Additional Useful Query Functions
# ============================================

def get_daily_revenue(days: int = 30) -> List[Dict[str, Any]]:
    """
    Get daily revenue report for the past N days.
    
    Args:
        days: Number of days to include in report.
        
    Returns:
        List of dictionaries with daily revenue data.
    """
    query = """
        SELECT 
            o.order_date,
            COUNT(o.order_id) AS order_count,
            ROUND(SUM(o.subtotal), 2) AS subtotal,
            ROUND(SUM(o.tax), 2) AS tax,
            ROUND(SUM(o.tip), 2) AS tips,
            ROUND(SUM(o.total), 2) AS daily_total
        FROM orders o
        WHERE o.status = 'Completed'
        GROUP BY o.order_date
        ORDER BY o.order_date DESC
        LIMIT ?
    """
    
    with get_db_cursor() as (conn, cursor):
        cursor.execute(query, (days,))
        results = cursor.fetchall()
        return [dict(row) for row in results]


def get_revenue_by_category() -> List[Dict[str, Any]]:
    """
    Get revenue breakdown by menu category.
    
    Returns:
        List of dictionaries with category revenue data.
    """
    query = """
        SELECT 
            c.name AS category,
            COUNT(DISTINCT oi.order_id) AS order_count,
            SUM(oi.quantity) AS items_sold,
            ROUND(SUM(oi.quantity * oi.unit_price), 2) AS category_revenue
        FROM categories c
        JOIN menu_items mi ON c.category_id = mi.category_id
        JOIN order_items oi ON mi.item_id = oi.item_id
        JOIN orders o ON oi.order_id = o.order_id
        WHERE o.status = 'Completed'
        GROUP BY c.category_id, c.name
        ORDER BY category_revenue DESC
    """
    
    with get_db_cursor() as (conn, cursor):
        cursor.execute(query)
        results = cursor.fetchall()
        return [dict(row) for row in results]


def get_upcoming_reservations() -> List[Dict[str, Any]]:
    """
    Get all upcoming confirmed reservations.
    
    Returns:
        List of dictionaries with reservation data.
    """
    query = """
        SELECT 
            r.reservation_id,
            r.reservation_date,
            r.reservation_time,
            c.first_name || ' ' || c.last_name AS customer_name,
            c.phone,
            t.table_number,
            t.location,
            r.party_size,
            r.status,
            r.special_requests
        FROM reservations r
        JOIN customers c ON r.customer_id = c.customer_id
        JOIN tables t ON r.table_id = t.table_id
        WHERE r.reservation_date >= DATE('now')
          AND r.status = 'Confirmed'
        ORDER BY r.reservation_date, r.reservation_time
    """
    
    with get_db_cursor() as (conn, cursor):
        cursor.execute(query)
        results = cursor.fetchall()
        return [dict(row) for row in results]


def run_all_test_queries():
    """
    Execute and display results of all five test queries.
    """
    print("=" * 60)
    print("RESTAURANT DATABASE TEST QUERIES")
    print("=" * 60)
    
    # Query 1
    print("\n" + "=" * 60)
    print("QUERY 1: Revenue by Server")
    print("=" * 60)
    results = get_revenue_by_server()
    if results:
        print(f"{'Server Name':<25} {'Role':<12} {'Orders':<8} {'Revenue':>12}")
        print("-" * 60)
        for row in results[:10]:
            print(f"{row['server_name']:<25} {row['role']:<12} {row['total_orders']:<8} ${row['total_revenue']:>10.2f}")
    else:
        print("No data found.")
    
    # Query 2
    print("\n" + "=" * 60)
    print("QUERY 2: Most Popular Menu Items")
    print("=" * 60)
    results = get_popular_menu_items(10)
    if results:
        print(f"{'Item Name':<30} {'Category':<15} {'Times Ordered':>14}")
        print("-" * 60)
        for row in results:
            print(f"{row['item_name']:<30} {row['category']:<15} {row['times_ordered']:>14}")
    else:
        print("No data found.")
    
    # Query 3
    print("\n" + "=" * 60)
    print("QUERY 3: Customers Above Average Spending")
    print("=" * 60)
    results = get_above_average_customers()
    if results:
        avg = results[0]['avg_customer_spending'] if results else 0
        print(f"Average customer spending: ${avg:.2f}")
        print(f"\n{'Customer Name':<25} {'Orders':<8} {'Total Spent':>12}")
        print("-" * 50)
        for row in results[:10]:
            print(f"{row['customer_name']:<25} {row['order_count']:<8} ${row['total_spent']:>10.2f}")
    else:
        print("No data found.")
    
    # Query 4
    print("\n" + "=" * 60)
    print("QUERY 4: Overbooked Reservations (Party > Table Capacity)")
    print("=" * 60)
    results = get_overbooked_reservations()
    if results:
        print(f"{'Customer':<20} {'Table':<8} {'Capacity':<10} {'Party Size':<12}")
        print("-" * 50)
        for row in results:
            print(f"{row['customer_name']:<20} {row['table_number']:<8} {row['table_capacity']:<10} {row['party_size']:<12}")
    else:
        print("No overbooked reservations found (this is good!).")
    
    # Query 5 (Preview only - don't actually update)
    print("\n" + "=" * 60)
    print("QUERY 5: Preview Price Increase for Entrees (10%)")
    print("=" * 60)
    results = get_category_prices("Entrees")
    if results:
        print(f"{'Item Name':<35} {'Current Price':>14} {'After 10%':>14}")
        print("-" * 65)
        for row in results:
            new_price = round(row['price'] * 1.10, 2)
            print(f"{row['name']:<35} ${row['price']:>12.2f} ${new_price:>12.2f}")
    else:
        print("No items found in Entrees category.")
    
    print("\n" + "=" * 60)
    print("All test queries completed successfully!")
    print("=" * 60)


if __name__ == "__main__":
    run_all_test_queries()

