-- ============================================
-- Restaurant Database Test Queries
-- CSC 4402 Database Project
-- ============================================

-- ============================================
-- QUERY 1: Total Revenue by Server
-- Joins orders, order_items, menu_items, and employees
-- to calculate total revenue generated by each server
-- ============================================
SELECT 
    e.employee_id,
    e.first_name || ' ' || e.last_name AS server_name,
    e.role,
    COUNT(DISTINCT o.order_id) AS total_orders,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS gross_sales,
    ROUND(SUM(o.tip), 2) AS total_tips,
    ROUND(SUM(o.total), 2) AS total_revenue
FROM employees e
JOIN orders o ON e.employee_id = o.employee_id
JOIN order_items oi ON o.order_id = oi.order_id
WHERE o.status = 'Completed'
GROUP BY e.employee_id, e.first_name, e.last_name, e.role
ORDER BY total_revenue DESC;


-- ============================================
-- QUERY 2: Most Popular Menu Items
-- Counts how many times each menu item appears in orders
-- Grouped and sorted by order count
-- ============================================
SELECT 
    mi.item_id,
    mi.name AS item_name,
    c.name AS category,
    mi.price,
    COUNT(oi.order_item_id) AS times_ordered,
    SUM(oi.quantity) AS total_quantity_sold,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_revenue
FROM menu_items mi
JOIN order_items oi ON mi.item_id = oi.item_id
JOIN categories c ON mi.category_id = c.category_id
JOIN orders o ON oi.order_id = o.order_id
WHERE o.status = 'Completed'
GROUP BY mi.item_id, mi.name, c.name, mi.price
ORDER BY times_ordered DESC
LIMIT 15;


-- ============================================
-- QUERY 3: Customers Who Spent More Than Average (Subquery)
-- Uses a subquery to find the average customer total
-- Then finds all customers who exceeded that average
-- ============================================
SELECT 
    c.customer_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    c.email,
    COUNT(o.order_id) AS order_count,
    ROUND(SUM(o.total), 2) AS total_spent,
    ROUND((SELECT AVG(customer_total) 
           FROM (SELECT SUM(total) AS customer_total 
                 FROM orders 
                 WHERE customer_id IS NOT NULL AND status = 'Completed'
                 GROUP BY customer_id)), 2) AS avg_customer_spending
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
WHERE o.status = 'Completed'
GROUP BY c.customer_id, c.first_name, c.last_name, c.email
HAVING SUM(o.total) > (
    SELECT AVG(customer_total) 
    FROM (SELECT SUM(total) AS customer_total 
          FROM orders 
          WHERE customer_id IS NOT NULL AND status = 'Completed'
          GROUP BY customer_id)
)
ORDER BY total_spent DESC;


-- ============================================
-- QUERY 4: Reservations Where Party Size Exceeds Table Capacity
-- Finds potential overbooking issues
-- Note: This should normally return empty if data is valid
-- ============================================
SELECT 
    r.reservation_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    c.phone,
    t.table_number,
    t.capacity AS table_capacity,
    r.party_size,
    r.reservation_date,
    r.reservation_time,
    r.status,
    r.special_requests
FROM reservations r
JOIN customers c ON r.customer_id = c.customer_id
JOIN tables t ON r.table_id = t.table_id
WHERE r.party_size > t.capacity
ORDER BY r.reservation_date, r.reservation_time;

-- Alternative: Find reservations for a specific date (parameterized)
-- Replace 'YYYY-MM-DD' with actual date
-- SELECT * FROM reservations WHERE reservation_date = 'YYYY-MM-DD';


-- ============================================
-- QUERY 5: Update Prices for a Category
-- Increases prices of all items in a category by 10%
-- ============================================
-- First, let's see current prices in Entrees category
SELECT 
    mi.name,
    c.name AS category,
    mi.price AS current_price,
    ROUND(mi.price * 1.10, 2) AS new_price_after_10_percent_increase
FROM menu_items mi
JOIN categories c ON mi.category_id = c.category_id
WHERE c.name = 'Entrees';

-- To actually perform the update (uncomment to execute):
-- UPDATE menu_items
-- SET price = ROUND(price * 1.10, 2)
-- WHERE category_id = (SELECT category_id FROM categories WHERE name = 'Entrees');


-- ============================================
-- ADDITIONAL USEFUL QUERIES
-- ============================================

-- Daily Revenue Report
SELECT 
    o.order_date,
    COUNT(o.order_id) AS order_count,
    ROUND(SUM(o.subtotal), 2) AS subtotal,
    ROUND(SUM(o.tax), 2) AS tax,
    ROUND(SUM(o.tip), 2) AS tips,
    ROUND(SUM(o.total), 2) AS daily_total
FROM orders o
WHERE o.status = 'Completed'
GROUP BY o.order_date
ORDER BY o.order_date DESC
LIMIT 30;


-- Revenue by Category
SELECT 
    c.name AS category,
    COUNT(DISTINCT oi.order_id) AS order_count,
    SUM(oi.quantity) AS items_sold,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS category_revenue
FROM categories c
JOIN menu_items mi ON c.category_id = mi.category_id
JOIN order_items oi ON mi.item_id = oi.item_id
JOIN orders o ON oi.order_id = o.order_id
WHERE o.status = 'Completed'
GROUP BY c.category_id, c.name
ORDER BY category_revenue DESC;


-- Upcoming Reservations
SELECT 
    r.reservation_date,
    r.reservation_time,
    c.first_name || ' ' || c.last_name AS customer_name,
    c.phone,
    t.table_number,
    t.location,
    r.party_size,
    r.status,
    r.special_requests
FROM reservations r
JOIN customers c ON r.customer_id = c.customer_id
JOIN tables t ON r.table_id = t.table_id
WHERE r.reservation_date >= DATE('now')
  AND r.status = 'Confirmed'
ORDER BY r.reservation_date, r.reservation_time;


-- Employee Schedule for This Week
SELECT 
    e.first_name || ' ' || e.last_name AS employee_name,
    e.role,
    s.shift_date,
    s.start_time,
    s.end_time
FROM employees e
JOIN shifts s ON e.employee_id = s.employee_id
WHERE s.shift_date BETWEEN DATE('now') AND DATE('now', '+7 days')
ORDER BY s.shift_date, s.start_time, e.last_name;


-- Table Utilization (which tables are most reserved)
SELECT 
    t.table_number,
    t.location,
    t.capacity,
    COUNT(r.reservation_id) AS total_reservations,
    SUM(CASE WHEN r.status = 'Completed' THEN 1 ELSE 0 END) AS completed,
    SUM(CASE WHEN r.status = 'Cancelled' THEN 1 ELSE 0 END) AS cancelled,
    SUM(CASE WHEN r.status = 'No-Show' THEN 1 ELSE 0 END) AS no_shows
FROM tables t
LEFT JOIN reservations r ON t.table_id = r.table_id
GROUP BY t.table_id, t.table_number, t.location, t.capacity
ORDER BY total_reservations DESC;

